spring.application.name=Hotel-booking-API

# DATABASE CONFIG

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=Omj@2572
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.fomat_sql=true

#server
server.servlet.context-path=/api/v1
server.port=8080

# Jwt secret
jwt.secretKey=Z2hqa2xqZGpoa2xkamZoamtsamZoamts

#front-end url

#Stripe Configuration
stripe.secret.key= dummy_key
stripe.webhook.secret= dummy_key

spring.profiles.active=dev

